<a href="https://colab.research.google.com/github/avinashkumar18/Lab/blob/main/DWDM/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Github link](https://github.com/avinashkumar18/Lab/blob/main/DWDM/Numpy.ipynb)

In [ ]:
# importing numpy package
import numpy as np

In [ ]:
# 3 arrays with various dimensions
a = np.array([1,2,3])
b = np.array([(1.6,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.6,2,3), (4,5,6)], [(3,2,1), (7,8,9)]], dtype = float)

In [ ]:
print(np.zeros((3,4))) # creating zero array
print(np.ones((2,3,4),dtype=np.int16)) # creating ones array
d = np.arange(10,25,5) # creating array of even spaced values
print(d)
print(np.linspace(0,2,9)) # creates array within the interval
e = np.full((2,2),7) #  creates array one int (r,c),n
print(e)
f = np.eye(2, dtype=int) # creates array with 1 in diagonal
print(f)
print(np.random.random((2,2))) # creates array with random numbers
print(np.empty((3,2))) # creates array with arbitrary data

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.27738773 0.36433361]
 [0.49507667 0.83339031]]
[[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


In [ ]:
# data types
print(np.int64)
print(np.float32)
print(np.complex)
print(np.bool)
print(np.object)
print(np.string_)
print( np.unicode_)

<class 'numpy.int64'>
<class 'numpy.float32'>
<class 'complex'>
<class 'bool'>
<class 'object'>
<class 'numpy.bytes_'>
<class 'numpy.str_'>


In [ ]:
print(a.shape)
print(len(a))
print(b.ndim)
print(e.size)
print(b.dtype)
print(b.dtype.name)
print(b.astype(int))

(3,)
3
2
4
float64
float64
[[1 2 3]
 [4 5 6]]


In [ ]:
# general arithmetic
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[2.6 4.  6. ]
 [5.  7.  9. ]]
[[-0.6  0.   0. ]
 [-3.  -3.  -3. ]]
[[ 1.6  4.   9. ]
 [ 4.  10.  18. ]]
[[0.625 1.    1.   ]
 [0.25  0.4   0.5  ]]


In [ ]:
print("exp of a: ", np.exp(a))
print("sqrt of b: ", np.sqrt(b))
print("sin of c: ", np.sin(c))
print("cos of d: ", np.cos(d))
print("tan of a: ", np.tan(a))
print("log of c: ", np.log(c))

exp of a:  [ 2.71828183  7.3890561  20.08553692]
sqrt of b:  [[1.26491106 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
sin of c:  [[[ 0.9995736   0.90929743  0.14112001]
  [-0.7568025  -0.95892427 -0.2794155 ]]

 [[ 0.14112001  0.90929743  0.84147098]
  [ 0.6569866   0.98935825  0.41211849]]]
cos of d:  [-0.83907153 -0.75968791  0.40808206]
tan of a:  [ 1.55740772 -2.18503986 -0.14254654]
log of c:  [[[0.47000363 0.69314718 1.09861229]
  [1.38629436 1.60943791 1.79175947]]

 [[1.09861229 0.69314718 0.        ]
  [1.94591015 2.07944154 2.19722458]]]


In [ ]:
# comparison operator
print(a==b)
print(a<2)
print(np.array_equal(b,c))

[[False  True  True]
 [False False False]]
[ True False False]
False


In [ ]:
print(a.sum()) #sum
print(b.min(axis=0), b.min(axis=1)) #min axis=row
print(c.max()) #max
print(b.cumsum()) #cummulative sum
print(a.mean()) #mean
print(np.median(b)) #median
print(np.corrcoef(b)) #correlation coefficient
print(np.std(c))

6
[1.6 2.  3. ] [1.6 4. ]
9.0
[ 1.6  3.6  6.6 10.6 15.6 21.6]
2.0
3.5
[[1.         0.97072534]
 [0.97072534 1.        ]]
2.560598888281151
