<a href="https://colab.research.google.com/github/avinashkumar18/Lab/blob/main/MLT_Lab/Lab_3_Analysing_simple_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Machine Learning Lab Assignment

Implementation of Simple ML Model

Name: Avinash Kumar K R

Reg No.: 20MAI0035

In [ ]:
# importing packages
import numpy as np
from sklearn.datasets import load_breast_cancer
import pandas as pd

In [ ]:
# import cancer dataset
cancer_ds = load_breast_cancer()

In [ ]:
# set the predictor and target variables
X = cancer_ds.data
Y = cancer_ds.target

In [ ]:
print(X)
print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

In [ ]:
data = pd.DataFrame(cancer_ds.data, columns = cancer_ds['feature_names'])

In [ ]:
# setting class column as target variable
data['class'] = cancer_ds.target

In [ ]:
data.head()

mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

In [ ]:
# how many malignant or benign?
# count of binary variable - class column
data['class'].value_counts()

1    357
0    212
Name: class, dtype: int64

In [ ]:
# knowing target names
cancer_ds.target_names

array(['malignant', 'benign'], dtype='<U9')

In [ ]:
data.groupby('class').mean()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
class                             ...                                         
0        17.462830     21.604906  ...        0.323468                 0.091530
1        12.146524     17.914762  ...        0.270246                 0.079442

[2 rows x 30 columns]

In [ ]:
# we can also groupby some other column but choose the target column for grouping
data.groupby('mean perimeter').mean()

mean radius  mean texture  ...  worst fractal dimension  class
mean perimeter                             ...                                
43.79                 6.981         13.43  ...                  0.09382    1.0
47.92                 7.760         24.54  ...                  0.07039    1.0
47.98                 7.729         25.49  ...                  0.09938    1.0
48.34                 7.691         25.44  ...                  0.10660    1.0
51.71                 8.196         16.84  ...                  0.07409    1.0
...                     ...           ...  ...                      ...    ...
171.50               25.220         24.91  ...                  0.10510    0.0
174.20               25.730         17.46  ...                  0.08815    0.0
182.10               27.220         21.87  ...                  0.08082    0.0
186.90               27.420         26.27  ...                  0.07427    0.0
188.50               28.110         18.47  ...                  0.05525    0.0

[522 rows x 30 columns]

***Train Test Split***

In [ ]:
# simple package that splits the train and test data
from sklearn.model_selection import train_test_split

In [ ]:
# dropping the target column
X = data.drop('class', axis=1)
Y = data['class']

In [ ]:
#splitting X and Y
# test size - size of test dataset
# stratify - will giive correct propotion of split among categorical variables(0 and 1 in this case)
# random state - preserves the split shuffling
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.15, stratify=Y, random_state = 2 )

In [ ]:
print(Y.shape, Y_train.shape, Y_test.shape)

(569,) (483,) (86,)


In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(569, 30) (483, 30) (86, 30)


In [ ]:
print(X.mean(), X_train.mean(), X_test.mean())

mean radius                 14.127292
mean texture                19.289649
mean perimeter              91.969033
mean area                  654.889104
mean smoothness              0.096360
mean compactness             0.104341
mean concavity               0.088799
mean concave points          0.048919
mean symmetry                0.181162
mean fractal dimension       0.062798
radius error                 0.405172
texture error                1.216853
perimeter error              2.866059
area error                  40.337079
smoothness error             0.007041
compactness error            0.025478
concavity error              0.031894
concave points error         0.011796
symmetry error               0.020542
fractal dimension error      0.003795
worst radius                16.269190
worst texture               25.677223
worst perimeter            107.261213
worst area                 880.583128
worst smoothness             0.132369
worst compactness            0.254265
worst concav

In [ ]:
# providing different case below
X_trains, X_tests, Y_trains, Y_tests = train_test_split(X,Y,test_size=0.20, random_state = 5 )
print(Y.shape, Y_trains.shape, Y_tests.shape)
print(X.shape, X_trains.shape, X_tests.shape)

(569,) (455,) (114,)
(569, 30) (455, 30) (114, 30)


In [ ]:
print(X.mean(), X_trains.mean(), X_tests.mean())

mean radius                 14.127292
mean texture                19.289649
mean perimeter              91.969033
mean area                  654.889104
mean smoothness              0.096360
mean compactness             0.104341
mean concavity               0.088799
mean concave points          0.048919
mean symmetry                0.181162
mean fractal dimension       0.062798
radius error                 0.405172
texture error                1.216853
perimeter error              2.866059
area error                  40.337079
smoothness error             0.007041
compactness error            0.025478
concavity error              0.031894
concave points error         0.011796
symmetry error               0.020542
fractal dimension error      0.003795
worst radius                16.269190
worst texture               25.677223
worst perimeter            107.261213
worst area                 880.583128
worst smoothness             0.132369
worst compactness            0.254265
worst concav

23/02/2021 Lab session 4

In [ ]:
#Binarization of input
X_binarised_train = X_train.apply(pd.cut, bins=2, labels=[1,0]) 
X_binarised_test = X_test.apply(pd.cut, bins=2, labels=[1,0])

In [ ]:
X_binarised_train = X_binarised_train.values
X_binarised_test = X_binarised_test.values

In [ ]:
print(X_binarised_train) 
print(X_binarised_test)
type(X_binarised_train)

[[1 1 1 ... 1 1 1]
 [1 0 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 0 1 1]
 [1 1 1 ... 0 1 1]]
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [0 1 0 ... 0 1 1]
 [0 1 0 ... 1 1 1]]


numpy.ndarray

In [ ]:
# predicting the accuracy for every scenario
print("num    acc_rows     accuracy")
for num in range (X_binarised_train.shape[1]+1):
  accurate_rows= 0
  for x,y in zip(X_binarised_train, Y_train):
    y_pred = (np.sum(x)>=num)
    accurate_rows += (y==y_pred)
  print(num,'\t', accurate_rows,'\t',accurate_rows/X_binarised_train.shape[0])

num    acc_rows     accuracy
0 	 303 	 0.6273291925465838
1 	 303 	 0.6273291925465838
2 	 303 	 0.6273291925465838
3 	 303 	 0.6273291925465838
4 	 303 	 0.6273291925465838
5 	 303 	 0.6273291925465838
6 	 303 	 0.6273291925465838
7 	 303 	 0.6273291925465838
8 	 303 	 0.6273291925465838
9 	 303 	 0.6273291925465838
10 	 303 	 0.6273291925465838
11 	 303 	 0.6273291925465838
12 	 303 	 0.6273291925465838
13 	 304 	 0.629399585921325
14 	 305 	 0.6314699792960663
15 	 306 	 0.6335403726708074
16 	 310 	 0.6418219461697723
17 	 315 	 0.6521739130434783
18 	 319 	 0.660455486542443
19 	 321 	 0.6645962732919255
20 	 328 	 0.6790890269151139
21 	 331 	 0.6853002070393375
22 	 340 	 0.7039337474120083
23 	 358 	 0.7412008281573499
24 	 371 	 0.7681159420289855
25 	 384 	 0.7950310559006211
26 	 394 	 0.8157349896480331
27 	 409 	 0.8467908902691511
28 	 408 	 0.84472049689441
29 	 389 	 0.8053830227743272
30 	 349 	 0.722567287784679


In [ ]:
# above provides row 27 and 28 show most accurate values
# find test accuracy for num = 27 and 28
print("num    acc_rows     accuracy")
for num in range (27,29):
  accurate_rows= 0
  for x,y in zip(X_binarised_train, Y_test):
      y_pred = (np.sum(x)>=num)
      accurate_rows += (y==y_pred)
  print(num, '\t', accurate_rows, '\t', accurate_rows/X_binarised_test.shape[0])

num    acc_rows     accuracy
27 	 50 	 0.5813953488372093
28 	 48 	 0.5581395348837209


MAX ACCURACY (num=27)

1.   Train - 84%
2.   Test  - 58%
